### ISSUE TITLE
Collapse subtree

### ISSUE THREAD

**Issue by ArnaudBarre** [rschristian/deptree#4]
Me again, following #3, I would like to be able to collapse tree I already know (ex `@typescript-eslint`) to be able to look at the other dependency more easily.

**Comment by hacknug** [comment]
Probably not what you want but I'm hiding unflagged branches using css:

```css
pre.w-max ~ div:not(:has(.decoration-2)) {
  display: none;
}
```

<details><summary>This is what it looks like 👇 </summary>
<img src="https://github.com/user-attachments/assets/16cd1d07-1e06-446f-aa24-84567f0322a1">
</details>

I can open a PR adding an option to toggle this if @rschristian thinks it would be helpful 👍
